# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  name: 'Noteworx'
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image

  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          set -x
          pwd
          ls -lrt
          echo 'Hello world'
          # docker rmi -f $(docker images -q) || true
          docker rmi -f $(docker images | grep anilappari | awk '{print $3}')
          docker system prune -f
          docker build -f dockerfiles/Dockerfile.be -t anilappari/noteworkxbe:$(tag) .
          docker build -f dockerfiles/Dockerfile.fe -t anilappari/noteworkxfe:$(tag) .
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'DH'
    #     repository: 'anilappari/noteworkxbe'
    #     command: 'buildAndPush'
    #     Dockerfile: 'dockerfiles/Dockerfile.be'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'DH'
    #     repository: 'anilappari/noteworkxfe'
    #     command: 'buildAndPush'
    #     Dockerfile: 'dockerfiles/Dockerfile.fe'
