# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  name: 'Noteworx'
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image

  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: Docker@2
      inputs:
        containerRegistry: 'DH'
        repository: 'amilappari/noteworkxbe'
        command: 'buildAndPush'
        Dockerfile: 'dockerfiles/Dockerfile.be'
    - task: Docker@2
      inputs:
        containerRegistry: 'DH'
        repository: 'amilappari/noteworkxfe'
        command: 'buildAndPush'
        Dockerfile: 'dockerfiles/Dockerfile.fe'
