services:
  mongodb:
    image: mongodb/mongodb-community-server:4.4.3-ubuntu2004-20230514T053842Z
    restart: always
    # ports:
    #   - 27017:27017
  backend:
    container_name: backend
    # image: anilappari/noteworkx:be-1.00
    image: anilappari/noteworkxbe:1.02
    # command: "npm run serve:api"
    ports:
      - 8000:8000
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - PORT=8000
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    image: anilappari/noteworkx:fe-1.00
    ports:
      - 80:80
    environment:
      - API_URL=http://backend:8000/api
    depends_on:
      - backend
    